version: 2
jobs:
  build:
    working_directory: ~/yoga2
    docker:
      # Node 8 LTS
      - image: circleci/node:carbon
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: yarn install
      - run:
          name: install-package-dependencies
          command: yarn run bootstrap
      - run:
          name: run-build
          command: yarn run build
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: run lint
          command: yarn run lint
